[project]
name = "quantum-app-benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["qiskit-aer~=0.16", "qiskit~=1.0"]

[project.optional-dependencies]
VQE = ["qiskit-nature[pyscf]>=0.7.2"]
QSVM = ["scikit-image>=0.25.1"]
IBM = ["qiskit-ibm-runtime>=0.36.1"]
AQT = ["qiskit-aqt-provider>=1.10.0"]

[dependency-groups]
dev = ["pytest>=8.3.4"]

[tool.pytest.ini_options]
pythonpath = "."

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"
