[project]
name = "qc_app_benchmarks"
version = "0.1.0"
authors = [
    { name = "Konrad Wojciechowski", email = "kwojciechowski@man.poznan.pl" },
]
description = "Package for running benchmarks on quantum backends leveraging Qiskit"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "qiskit>=1.0",
    "qiskit-aer>=0.13",
    "qiskit-ibm-runtime",
    # "qiskit-aqt-provider" 
]

[project.optional-dependencies]
VQE = ["qiskit-nature~=0.7", "pyscf"]
QSVM = ["scikit-image==0.21"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["qc_app_benchmarks*"]

[tool.setuptools.package-data]
qc_app_benchmarks = ["*.csv"]
